### ISSUE TITLE
Naming convention to discuss

### ISSUE THREAD

**Issue by simplewepro** [LMD-inc/teleportation-runes#1]
The most often naming for Block Entity classes I've met is BEBlockname (having BE all capitalized, i.e. `BEBehaviorAnimatable` class from game api). As well as for folders in `src` folder to be capitalized as well. What do you think about it?

https://github.com/LMD-inc/teleportation-runes/blob/d56491cb04c8ed46174fb153608d317ddd80189b/src/TeleportationRunes.cs#L17

**Comment by snakeriot** [comment]
Makes sense since each letter in BE means separate word, and therefore should have same case.
Updated code base
